version: "3.0"
    
services:
  edt:
    image: ghcr.io/linuxserver/code-server
    container_name: sl-edt
    env_file:
      - .env
    environment:
      - PUID=${PUID:-default}
      - PGID=${PGID:-default}
      - TZ=America/Fortaleza
      - PASSWORD=${EDT_PASSWORD:-default}
#      - HASHED_PASSWORD= #optional
      - SUDO_PASSWORD=${EDT_SUDO_PASSWORD:-default}
      - SUDO_PASSWORD_HASH= #optional
#      - PROXY_DOMAIN=code-server.salvador.eti
    volumes:
      - ${PWD}/config:/config
#      - ${PWD}/config:/app
      - ${HOME}/.ssh:/config/.ssh
      - ${PWD}:/home/abc/slider
    ports:
      - 8443:8443
#      - 3030:3000
    restart: unless-stopped


  adm:
    image: phpmyadmin
    container_name: sl-adm
    ports:
      - 8081:80
    environment:
      - PUID=${PUID:-default}
      - PGID=${PGID:-default}
      - PMA_ARBITRARY=1
    restart: always

  db:
    image: mariadb
    container_name: sl-db
    volumes:
      - db_data:/var/lib/mysql
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-default}
      MYSQL_DATABASE: ${MYSQL_DATABASE:-default}
      MYSQL_USER: ${MYSQL_USER:-default}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-default}
    restart: always

  wp:
    image: wordpress
    container_name: sl-wp
    depends_on:
      - db
    volumes:
      - ${PWD}/html:/var/www/html
    ports:
      - 80:80
    env_file:
      - .env
    environment:
      PUID: ${PUID:-default}
      PGID: ${PGID:-default}
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_NAME: ${MYSQL_DATABASE:-default}
      WORDPRESS_DB_USER: ${MYSQL_USER:-default}
      WORDPRESS_DB_PASSWORD: ${MYSQL_PASSWORD:-default}
    restart: always

volumes:
  db_data: {}
